// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTOP.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class VTOP___024unit;


class VTOP__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTOP___024root final : public VerilatedModule {
  public:
    // CELLS
    VTOP___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_commit_rd,4,0);
        VL_OUT8(io_commit_wen,0,0);
        VL_OUT8(io_commit_commit,0,0);
        VL_OUT8(io_commit_halt,0,0);
        CData/*0:0*/ TOP__DOT__IF_io_Pre2IF_valid;
        CData/*0:0*/ TOP__DOT__IF_io_IF2ID_ready;
        CData/*0:0*/ TOP__DOT__IF_io_IF2ID_valid;
        CData/*0:0*/ TOP__DOT__IF_io_brTaken;
        CData/*0:0*/ TOP__DOT__IF_io_pcBrEnable;
        CData/*0:0*/ TOP__DOT__IF_io_pcBrRecord;
        CData/*0:0*/ TOP__DOT__ID_io_ID2EX_ready;
        CData/*1:0*/ TOP__DOT__ID_io_ID2EX_bits_aluSrc2;
        CData/*1:0*/ TOP__DOT__EX_io_hazard1;
        CData/*1:0*/ TOP__DOT__EX_io_hazard2;
        CData/*0:0*/ TOP__DOT__EX_io_stall;
        CData/*0:0*/ TOP__DOT__MEM_io_MEM2WB_ready;
        CData/*0:0*/ TOP__DOT__MEM_io_MEM2WB_valid;
        CData/*0:0*/ TOP__DOT__WB_io_WBout_valid;
        CData/*0:0*/ TOP__DOT__InstRam_arvalid;
        CData/*0:0*/ TOP__DOT__Pre2IFValid;
        CData/*0:0*/ TOP__DOT__IF2IDValid;
        CData/*0:0*/ TOP__DOT__ID2EXValid;
        CData/*0:0*/ TOP__DOT__EX2MEMValid;
        CData/*0:0*/ TOP__DOT__MEM2WBValid;
        CData/*0:0*/ TOP__DOT__arFireReg;
        CData/*0:0*/ TOP__DOT___Pre2IFValid_T_2;
        CData/*0:0*/ TOP__DOT__IFoutValid;
        CData/*0:0*/ TOP__DOT___ID_io_IF2ID_bits_T_1;
        CData/*0:0*/ TOP__DOT__IDoutValid;
        CData/*0:0*/ TOP__DOT___EX_io_ID2EX_bits_T_1;
        CData/*2:0*/ TOP__DOT__EX_io_ID2EX_bits_r_func3;
        CData/*0:0*/ TOP__DOT__EX_io_ID2EX_bits_r_memWrite;
        CData/*0:0*/ TOP__DOT__EX_io_ID2EX_bits_r_memRead;
        CData/*4:0*/ TOP__DOT__EX_io_ID2EX_bits_r_rs1;
        CData/*4:0*/ TOP__DOT__EX_io_ID2EX_bits_r_rs2;
        CData/*4:0*/ TOP__DOT__EX_io_ID2EX_bits_r_rd;
        CData/*0:0*/ TOP__DOT__EX_io_ID2EX_bits_r_regWrite;
        CData/*3:0*/ TOP__DOT__EX_io_ID2EX_bits_r_aluOp;
        CData/*1:0*/ TOP__DOT__EX_io_ID2EX_bits_r_aluSrc1;
        CData/*1:0*/ TOP__DOT__EX_io_ID2EX_bits_r_aluSrc2;
        CData/*1:0*/ TOP__DOT__EX_io_ID2EX_bits_r_pcSrc;
        CData/*0:0*/ TOP__DOT__EX_io_ID2EX_bits_r_jump;
        CData/*0:0*/ TOP__DOT__EX_io_ID2EX_bits_r_halt;
        CData/*0:0*/ TOP__DOT__MEMRegWrite;
        CData/*0:0*/ TOP__DOT__WBRegWrite;
        CData/*0:0*/ TOP__DOT__hazard1_1;
        CData/*0:0*/ TOP__DOT__hazard2_1;
        CData/*0:0*/ TOP__DOT__EXoutValid;
        CData/*0:0*/ TOP__DOT___MEM_io_EX2MEM_bits_T_1;
        CData/*2:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_func3;
        CData/*0:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_memWrite;
        CData/*0:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_memRead;
        CData/*4:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_rd;
        CData/*0:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_regWrite;
        CData/*0:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_halt;
        CData/*0:0*/ TOP__DOT___EX2MEMValid_T_2;
        CData/*0:0*/ TOP__DOT__MEMoutValid;
        CData/*0:0*/ TOP__DOT___WB_io_MEM2WB_bits_T_1;
        CData/*2:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_func3;
        CData/*0:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_memRead;
        CData/*0:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_memWrite;
        CData/*4:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_rd;
    };
    struct {
        CData/*0:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_regWrite;
        CData/*0:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_halt;
        CData/*0:0*/ TOP__DOT__IF__DOT__pcBrEnableReg;
        CData/*0:0*/ TOP__DOT__IF__DOT__pcBrRecordReg;
        CData/*0:0*/ TOP__DOT__IF__DOT__brBufferValid;
        CData/*0:0*/ TOP__DOT__IF__DOT___pcBrRecordReg_T;
        CData/*0:0*/ TOP__DOT__IF__DOT___pcReg_T;
        CData/*0:0*/ TOP__DOT__IF__DOT__rFireReg;
        CData/*0:0*/ TOP__DOT__IF__DOT___rFireReg_T_1;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_T;
        CData/*7:0*/ TOP__DOT__ID__DOT___DecoderOut_T_2;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_T_6;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_T_8;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_T_19;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_T_25;
        CData/*3:0*/ TOP__DOT__ID__DOT___DecoderOut_T_28;
        CData/*6:0*/ TOP__DOT__ID__DOT___DecoderOut_T_32;
        CData/*7:0*/ TOP__DOT__ID__DOT__DecoderOut_hi_lo_9;
        CData/*3:0*/ TOP__DOT__ID__DOT___DecoderOut_T_36;
        CData/*3:0*/ TOP__DOT__ID__DOT___DecoderOut_T_52;
        CData/*4:0*/ TOP__DOT__ID__DOT___DecoderOut_T_60;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_1;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_3;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_7;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_10;
        CData/*5:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_12;
        CData/*3:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_14;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_16;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_23;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_26;
        CData/*1:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_32;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_34;
        CData/*2:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_36;
        CData/*2:0*/ TOP__DOT__ID__DOT__Type;
        CData/*2:0*/ TOP__DOT__ID__DOT____VdfgTmp_h20af328f__0;
        CData/*5:0*/ TOP__DOT__ID__DOT____VdfgTmp_h77b1137a__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_h273547c4__0;
        CData/*6:0*/ TOP__DOT__ID__DOT____VdfgTmp_h35f65dd2__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_h1fa5bf6d__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_h89094836__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_hc297c6cf__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_h6398cd2a__0;
        CData/*1:0*/ TOP__DOT__ID__DOT____VdfgTmp_hf773fe7b__0;
        CData/*0:0*/ TOP__DOT__ID__DOT__Rf__DOT__Wen;
        CData/*0:0*/ TOP__DOT__EX__DOT__hazard1Reg;
        CData/*0:0*/ TOP__DOT__EX__DOT__hazard2Reg;
        CData/*0:0*/ TOP__DOT__EX__DOT___bypassReg_T;
        CData/*0:0*/ TOP__DOT__EX__DOT__brEnable;
        CData/*0:0*/ TOP__DOT__EX__DOT__brTaken;
        CData/*0:0*/ TOP__DOT__EX__DOT____VdfgTmp_h09a5d97f__0;
        CData/*0:0*/ TOP__DOT__EX__DOT____VdfgTmp_hc327c5e2__0;
        CData/*3:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T;
        CData/*3:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_2;
        CData/*3:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_4;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_6;
        CData/*2:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_8;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_10;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_12;
        CData/*2:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_14;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_16;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT___Operation_T_18;
        CData/*2:0*/ TOP__DOT__EX__DOT__Alu__DOT____VdfgTmp_hf12cf007__0;
        CData/*1:0*/ TOP__DOT__EX__DOT__Alu__DOT____VdfgTmp_h61253848__0;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__FillBit;
    };
    struct {
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__ShiftL;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__ShiftR;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_0;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_1;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_2;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_3;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_4;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_5;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_6;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_7;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_8;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_9;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_10;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_11;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_12;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_13;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_14;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_15;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_16;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_17;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_18;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_19;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_20;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_21;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_22;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_23;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_24;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_25;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_26;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_27;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_28;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_29;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_30;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_0__DOT__switch_31;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__ShiftL;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__ShiftR;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_0;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_1;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_2;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_3;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_4;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_5;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_6;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_7;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_8;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_9;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_10;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_11;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_12;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_13;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_14;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_15;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_16;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_17;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_18;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_19;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_20;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_21;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_22;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_23;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_24;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_25;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_26;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_27;
    };
    struct {
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_28;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_29;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_30;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_1__DOT__switch_31;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__ShiftL;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__ShiftR;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_0;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_1;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_2;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_3;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_4;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_5;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_6;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_7;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_8;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_9;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_10;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_11;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_12;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_13;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_14;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_15;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_16;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_17;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_18;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_19;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_20;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_21;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_22;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_23;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_24;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_25;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_26;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_27;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_28;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_29;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_30;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_2__DOT__switch_31;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__ShiftL;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__ShiftR;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_0;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_1;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_2;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_3;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_4;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_5;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_6;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_7;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_8;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_9;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_10;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_11;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_12;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_13;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_14;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_15;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_16;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_17;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_18;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_19;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_20;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_21;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_22;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_23;
    };
    struct {
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_24;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_25;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_26;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_27;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_28;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_29;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_30;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_3__DOT__switch_31;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_4__DOT__ShiftL;
        CData/*0:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_4__DOT__ShiftR;
        CData/*3:0*/ TOP__DOT__MEM__DOT__io_w_bits_wstrb_plaInput;
        CData/*0:0*/ TOP__DOT__MEM__DOT__arDataFireReg;
        CData/*0:0*/ TOP__DOT__MEM__DOT__awFireReg;
        CData/*0:0*/ TOP__DOT__MEM__DOT__wFireReg;
        CData/*0:0*/ TOP__DOT__MEM__DOT___arDataFireReg_T;
        CData/*0:0*/ TOP__DOT__WB__DOT__rdataSignal;
        CData/*0:0*/ TOP__DOT__WB__DOT__rDataFireReg;
        CData/*0:0*/ TOP__DOT__WB__DOT__bFireReg;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__rstate;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__awstate;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__wstate;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__nxt_rstate;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__nxt_awstate;
        CData/*2:0*/ TOP__DOT__InstRam__DOT__nxt_wstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__rstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__awstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__wstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__nxt_rstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__nxt_awstate;
        CData/*2:0*/ TOP__DOT__DataRam__DOT__nxt_wstate;
        CData/*0:0*/ __VdfgTmp_h599285c1__0;
        CData/*0:0*/ __VdfgTmp_h5634abfd__0;
        CData/*0:0*/ __VdfgTmp_h44a07bf5__0;
        CData/*0:0*/ __VdfgTmp_h4824211d__0;
        CData/*6:0*/ __Vtableidx2;
        CData/*5:0*/ __Vtableidx3;
        CData/*5:0*/ __Vtableidx4;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ TOP__DOT__ID__DOT___DecoderOut_T_4;
        SData/*8:0*/ TOP__DOT__ID__DOT___DecoderOut_T_30;
        SData/*9:0*/ TOP__DOT__ID__DOT___DecoderOut_orMatrixOutputs_T_5;
        SData/*10:0*/ TOP__DOT__ID__DOT____VdfgTmp_h6adb00ff__0;
        VL_OUT(io_commit_pc,31,0);
        VL_OUT(io_commit_inst,31,0);
        VL_OUT(io_commit_wdata,31,0);
        IData/*31:0*/ TOP__DOT__IF_io_pcBr;
        IData/*31:0*/ TOP__DOT__IF_io_pcNext;
        IData/*31:0*/ TOP__DOT__ID_io_IF2ID_bits_r_pc;
        IData/*31:0*/ TOP__DOT__ID_io_IF2ID_bits_r_inst;
        IData/*31:0*/ TOP__DOT__EX_io_ID2EX_bits_r_pc;
        IData/*31:0*/ TOP__DOT__EX_io_ID2EX_bits_r_inst;
        IData/*31:0*/ TOP__DOT__EX_io_ID2EX_bits_r_rdata1;
        IData/*31:0*/ TOP__DOT__EX_io_ID2EX_bits_r_rdata2;
        IData/*31:0*/ TOP__DOT__EX_io_ID2EX_bits_r_imm;
        IData/*31:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_pc;
        IData/*31:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_inst;
        IData/*31:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_rdata2;
        IData/*31:0*/ TOP__DOT__MEM_io_EX2MEM_bits_r_aluOut;
        IData/*31:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_pc;
        IData/*31:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_inst;
        IData/*31:0*/ TOP__DOT__WB_io_MEM2WB_bits_r_aluOut;
    };
    struct {
        IData/*31:0*/ TOP__DOT__IF__DOT__pcReg;
        IData/*31:0*/ TOP__DOT__IF__DOT__brBuffer;
        IData/*31:0*/ TOP__DOT__IF__DOT__rdataReg;
        IData/*31:0*/ TOP__DOT__ID__DOT___DecoderOut_T_62;
        IData/*31:0*/ TOP__DOT__ID__DOT___DecoderOut_T_64;
        IData/*21:0*/ TOP__DOT__ID__DOT__DecoderOut_orMatrixOutputs;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_0;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_1;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_2;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_3;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_4;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_5;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_6;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_7;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_8;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_9;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_10;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_11;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_12;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_13;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_14;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_15;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_16;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_17;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_18;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_19;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_20;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_21;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_22;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_23;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_24;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_25;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_26;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_27;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_28;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_29;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_30;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT__gprSeq_31;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT___GEN_45;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT___GEN_58;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT___GEN_77;
        IData/*31:0*/ TOP__DOT__ID__DOT__Rf__DOT___GEN_90;
        IData/*31:0*/ TOP__DOT__EX__DOT__Alu_io_B;
        IData/*31:0*/ TOP__DOT__EX__DOT__Alu_io_Result;
        IData/*31:0*/ TOP__DOT__EX__DOT__bypassReg;
        IData/*31:0*/ TOP__DOT__EX__DOT__data1;
        IData/*31:0*/ TOP__DOT__EX__DOT__data2;
        IData/*31:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter_io_din;
        IData/*31:0*/ TOP__DOT__EX__DOT__Alu__DOT__AdderB;
        IData/*31:0*/ TOP__DOT__EX__DOT__Alu__DOT__Shifter__DOT__SelectorNet_4_io_dout;
        IData/*31:0*/ TOP__DOT__WB__DOT__rdataShift0;
        IData/*31:0*/ TOP__DOT__WB__DOT__rdataShift1;
        IData/*31:0*/ TOP__DOT__InstRam__DOT__ReadDataReg;
        IData/*31:0*/ TOP__DOT__DataRam__DOT__ReadDataReg;
        IData/*31:0*/ __VactIterCount;
        QData/*33:0*/ TOP__DOT__EX__DOT__Alu__DOT___AdderOut_T_1;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VTOP__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTOP___024root(VTOP__Syms* symsp, const char* v__name);
    ~VTOP___024root();
    VL_UNCOPYABLE(VTOP___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
